name: Test Workflow

on: [ push, pull_request ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3

      - name: Upgrade PIP
        run: |
          python -m pip install --upgrade pip

      - name: Install coverage, flake8, and isort
        run: |
          python -m pip install coverage flake8 isort

      - name: Create virtual display
        run: |
          sudo apt-get install -y xvfb
          Xvfb :1 -screen 0 1600x1200x24 &

      - name: Run tests
        run: |
          export DISPLAY=':1.0'
          PYTHONPATH=$(pwd)/src python -m coverage run tests/test_play.py
          for file in tests/game/test_*\.py; do
            PYTHONPATH=$(pwd)/src python -m coverage run -a $file
          done
          python -m coverage report -m

      - name: Check coding style
        run: |
          python -m flake8 . --extend-ignore E501,E221 --exit-zero; echo
          python -m isort . --diff
