name: Test Workflow

on: [ push, pull_request ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3

      - name: Upgrade PIP and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r src/requirements.txt

      - name: Create virtual display
        run: |
          sudo apt-get install -y xvfb
          Xvfb :1 -screen 0 1600x1200x24 &

      - name: Run tests
        run: |
          export DISPLAY=':1.0'
          cd src/
          python -m coverage run tests.py
          python -m coverage report -m
